// auto-generated by services/codegen/src/frontendGenerators.js
// model=Article schemaChange.field=coverImage type=STRING

export interface Article {
  slug: string;
  title: string;
  description: string;
  body: string;
  coverImage: string;
}
