// auto-generated by services/codegen/src/frontendGenerators.js
// model=Article field=coverImage type=STRING

export const mockArticles = [
  { slug: "auto-1", coverImage: "mock-1" },
  { slug: "auto-2", coverImage: "mock-2" },
];
