// auto-generated by services/codegen/src/frontendGenerators.js
// model=Article field=coverImage type=STRING

export async function getArticleList() {
  const res = await fetch("/api/articles");
  if (!res.ok) throw new Error("Failed to fetch articles: " + res.status);
  return res.json();
}

export async function updateArticleCoverImage(slug, value) {
  const res = await fetch(`/api/articles/${slug}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ coverImage: value }),
  });
  if (!res.ok) throw new Error("Failed to update Article.coverImage: " + res.status);
  return res.json();
}
